-- =============================================================
-- 2026-08-10: create missing sepay_transactions / audit_logs
-- tables and their enum types. Idempotent — safe to re-run.
-- Fixes 500 errors on /admin/orders, /transactions,
-- /reconciliations, /reports/revenue, /audit-logs.
-- =============================================================

-- Enums ---------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'transaction_match_status') then
    create type public.transaction_match_status as enum (
      'UNMATCHED',
      'MATCHED',
      'WRONG_CODE',
      'REVIEWED'
    );
  end if;
end
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'resolution_action') then
    create type public.resolution_action as enum (
      'NONE',
      'LINK_MANUALLY',
      'ACCEPT',
      'REJECT',
      'REFUND_REQUIRED'
    );
  end if;
end
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'audit_entity_type') then
    create type public.audit_entity_type as enum (
      'USER',
      'MENU_CATEGORY',
      'MENU_ITEM',
      'ORDER',
      'PAYMENT',
      'SEPAY_TRANSACTION'
    );
  end if;
end
$$;

-- sepay_transactions -------------------------------------------
create table if not exists public.sepay_transactions (
  id uuid primary key default gen_random_uuid(),
  sepay_transaction_id varchar(64) not null unique,
  payment_id uuid,
  transaction_date timestamptz not null,
  code varchar(100),
  content text,
  amount_in bigint not null default 0,
  reference_code varchar(150),
  match_status public.transaction_match_status
    not null default 'UNMATCHED',
  difference_amount bigint,
  resolution_action public.resolution_action not null default 'NONE',
  resolution_note text,
  resolved_by_user_id uuid,
  resolved_at timestamptz,
  raw_payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),

  constraint sepay_transactions_payment_fk
    foreign key (payment_id)
    references public.payments(id)
    on update cascade
    on delete restrict,

  constraint sepay_transactions_resolved_by_fk
    foreign key (resolved_by_user_id)
    references public.users(id)
    on update cascade
    on delete set null,

  constraint sepay_transactions_amount_in_chk check (amount_in >= 0),

  constraint sepay_transactions_resolution_chk check (
    (resolution_action = 'NONE'
      and resolved_by_user_id is null
      and resolved_at is null)
    or
    (resolution_action <> 'NONE'
      and resolved_by_user_id is not null
      and resolved_at is not null)
  ),

  constraint sepay_transactions_match_payment_chk check (
    match_status <> 'MATCHED'
    or payment_id is not null
  )
);

create index if not exists sepay_transactions_payment_date_idx
  on public.sepay_transactions (payment_id, transaction_date desc)
  where payment_id is not null;

create index if not exists sepay_transactions_unmatched_received_idx
  on public.sepay_transactions (received_at desc);

create index if not exists sepay_transactions_code_idx
  on public.sepay_transactions (code);

create index if not exists sepay_transactions_reference_code_idx
  on public.sepay_transactions (reference_code);

-- audit_logs ----------------------------------------------------
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  action varchar(100) not null,
  entity_type public.audit_entity_type not null,
  entity_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint audit_logs_actor_user_fk
    foreign key (actor_user_id)
    references public.users(id)
    on update cascade
    on delete set null
);

create index if not exists audit_logs_entity_created_idx
  on public.audit_logs (entity_type, entity_id, created_at desc);

create index if not exists audit_logs_actor_created_idx
  on public.audit_logs (actor_user_id, created_at desc);
